In [62]:
import torch
from torch.autograd import Function

In [15]:
a = torch.arange(0.5, 9.5, 0.5)

In [16]:
a.reshape(-1,2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000],
        [2.5000, 3.0000],
        [3.5000, 4.0000],
        [4.5000, 5.0000],
        [5.5000, 6.0000],
        [6.5000, 7.0000],
        [7.5000, 8.0000],
        [8.5000, 9.0000]])

In [59]:
length = 3
b = torch.cat([torch.zeros([1,length-1]), torch.arange(1,length,1).reshape(1,-1)],0).t()

In [60]:
b

tensor([[0., 1.],
        [0., 2.]])

In [64]:
class MyReLU(Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input.clamp(min=0)

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input

# 使用自定义的ReLU激活函数
def relu(input):
    return MyReLU.apply(input)

# 测试自定义激活函数
input = torch.tensor([-1.0, 0.0, 1.0], requires_grad=True)
output = relu(input)
print(output)

tensor([0., 0., 1.], grad_fn=<MyReLUBackward>)
